Feature ETP-306:  Use Etendo UI Components updated in Copilot Subapp
etendosoftware/com.etendoerp.subapp.copilot pull request #3
Opened 2024-09-17 15:40 UTC by tomirodeghiero

2024-09-17 15:42 UTC, LuuchoRocha approved these changes

2024-09-17 15:45 UTC, tomirodeghiero commented on subapp/src/screens/home/index.tsx
> +                    type={'left-user'}
Thank you for the comment @LuuchoRocha! Solved :)

2024-09-18 12:07 UTC, sebastianbarrozo requested changes

2024-09-18 12:22 UTC, sebastianbarrozo approved these changes

2024-09-18 13:25 UTC, merged